# Introdução {-}

Embora a matemática acompanhe a humanidade desde os primórdios da civilização, 
o advento da computação levou o emprego da matemática a um nível de sem precendente
na história graças ao aparecimento do Software. Ela é a linguagem universal que criou o mundo digital. 
É a ferramenta que permite aos programadores dar vida aos **algoritmos**, as *receitas que ditam o comportamento dos computadores*.

Todas as linguagens de programação, em especial as fortemente tipadas, como `FORTRAN`,
`C`, `JAVA`, `PASCAL`, `Python` e mesmo `SQL` usam conceitos matemáticos para 
criar estruturas abstratas dentro dos computadores, os chamados **SOFTWARES**.

Esta disciplina tem o objetivo de demonstrar a utilidade dos conceitos matemáticos,
já conhecidos em sua maioria, no mundo da computação.


## Expressões Algébricas

All chapter sections start with a second-level (`##`) or higher heading followed by your section title, like the sections above and below here. You can have as many as you want within a chapter.

### An unnumbered section {.unnumbered}

Chapters and sections are numbered by default. To un-number a heading, add a `{.unnumbered}` or the shorter `{-}` at the end of the heading, like in this section.
